wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.15.11
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1695551473.24984
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      3:
      - 1
      - 7
      - 23
      4: 3.10.13
      5: 0.15.11
      6: 4.33.2
      8:
      - 1
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
learning_rate:
  desc: null
  value: 0.0006
epochs:
  desc: null
  value: 40
betas:
  desc: null
  value:
  - 0.9
  - 0.98
weight_decay:
  desc: null
  value: 0.4
device_type:
  desc: null
  value: gpu
precision:
  desc: null
  value: '16'
batch_size:
  desc: null
  value: 64
num_workers:
  desc: null
  value: 4
d_model:
  desc: null
  value: 386
n_layers:
  desc: null
  value: 6
vocab_size:
  desc: null
  value: 65
d_embed:
  desc: null
  value: 33
d_filter_mlp:
  desc: null
  value: 64
n_filter_layers:
  desc: null
  value: 4
context_length:
  desc: null
  value: 128
short_conv_size:
  desc: null
  value: 3
order:
  desc: null
  value: 2
pdrop_hyena:
  desc: null
  value: 0.0
pdrop_embed:
  desc: null
  value: 0.2
omega:
  desc: null
  value: 12
