

ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:23.09-py3
FROM ${BASE_IMAGE}
 
RUN apt-get update
RUN apt-get install sudo
RUN addgroup --gid 90013 gkoren
RUN groupmod --gid 3000 dip
RUN addgroup --gid 30 hardware
RUN adduser --disabled-password --gecos GECOS -u 90013 -gid 30 gkoren
RUN adduser gkoren sudo
RUN usermod -a -G hardware gkoren
RUN usermod -a -G hardware root
RUN usermod -a -G root gkoren
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER gkoren

WORKDIR /tmp/safari_build
COPY ./requirements_cont.txt /tmp/safari_build/
RUN pip install -r requirements_cont.txt
