

ARG BASE_IMAGE=nvcr.io/nvidia/pytorch:23.09-py3
FROM ${BASE_IMAGE}
 
# RUN apt-get update
# RUN apt-get install sudo
# RUN addgroup --gid 90013 gkoren
# RUN groupmod --gid 3000 dip
# RUN addgroup --gid 30 hardware
# RUN adduser --disabled-password --gecos GECOS -u 90013 -gid 30 gkoren
# RUN adduser gkoren sudo
# RUN usermod -a -G hardware gkoren
# RUN usermod -a -G hardware root
# RUN usermod -a -G root gkoren
# RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
# USER gkoren

WORKDIR /home/gkoren
COPY ./docker_bashrc.txt /home/gkoren/.bashrc
RUN source /home/gkoren/.bashrc


WORKDIR /tmp/safari_build
COPY ./requirements_cont.txt /tmp/safari_build/
RUN pip install -r requirements_cont.txt  &&\
    rm -rf /tmp/safari_build

WORKDIR /workspace/safari

# build
# docker buildx build -f Dockerfile_ws -t <IMAGE_NAME> .

# Run the container
# docker run --gpus all -it --rm --privileged -v $(pwd -P):/workspace/safari --shm-size=8g -p 8888:8888 -p 6006:6006 --ulimit memlock=-1 --ulimit stack=67108864 --device=/dev/snd "$IMAGE_NAME"




